### ISSUE TITLE
Rotate U30 PRo screen like U20 Pro

### ISSUE THREAD

**Issue by SckyzO** [LONGER3D/Alfawise_U30_Pro_Screen_FW#2]
Hey team, 

Do you know if it is possible to rotate default U30 Pro / LK4 Pro, and push U20 Pro firmware screen to our U30Pro ? And, if possible, to have a STL to print new screen support ? 
Why this question ? Lot of users want to add BL Touch support with screen integration (like U20 Pro), and is not possible with U30 Pro firmware screen without write code, and lot of modifications, but you have a super firmware on U20 Pro, and we will add this on our U30 Pro :) 

Regard,

**Comment by moonberry-pl** [comment]
Yes, it's possible both printers share this same display "T5UID1 is DGUS II software platform based on T5 CPU, it is design for low resolution UI application.".
